// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        (unknown)
// source: pullrequester.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PullRequest_Check_Pass int32

const (
	PullRequest_Check_UNKNOWN PullRequest_Check_Pass = 0
	PullRequest_Check_FAIL    PullRequest_Check_Pass = 1
	PullRequest_Check_PASS    PullRequest_Check_Pass = 2
)

// Enum value maps for PullRequest_Check_Pass.
var (
	PullRequest_Check_Pass_name = map[int32]string{
		0: "UNKNOWN",
		1: "FAIL",
		2: "PASS",
	}
	PullRequest_Check_Pass_value = map[string]int32{
		"UNKNOWN": 0,
		"FAIL":    1,
		"PASS":    2,
	}
)

func (x PullRequest_Check_Pass) Enum() *PullRequest_Check_Pass {
	p := new(PullRequest_Check_Pass)
	*p = x
	return p
}

func (x PullRequest_Check_Pass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullRequest_Check_Pass) Descriptor() protoreflect.EnumDescriptor {
	return file_pullrequester_proto_enumTypes[0].Descriptor()
}

func (PullRequest_Check_Pass) Type() protoreflect.EnumType {
	return &file_pullrequester_proto_enumTypes[0]
}

func (x PullRequest_Check_Pass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullRequest_Check_Pass.Descriptor instead.
func (PullRequest_Check_Pass) EnumDescriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{0, 0, 0}
}

type PullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url             string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	NumberOfCommits int32                `protobuf:"varint,2,opt,name=number_of_commits,json=numberOfCommits,proto3" json:"number_of_commits,omitempty"`
	Checks          []*PullRequest_Check `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	Shas            []string             `protobuf:"bytes,4,rep,name=shas,proto3" json:"shas,omitempty"`
	// The name of the underlying branch
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pullrequester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pullrequester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PullRequest) GetNumberOfCommits() int32 {
	if x != nil {
		return x.NumberOfCommits
	}
	return 0
}

func (x *PullRequest) GetChecks() []*PullRequest_Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *PullRequest) GetShas() []string {
	if x != nil {
		return x.Shas
	}
	return nil
}

func (x *PullRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastRun  int64          `protobuf:"varint,1,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	Tracking []*PullRequest `protobuf:"bytes,2,rep,name=tracking,proto3" json:"tracking,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pullrequester_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pullrequester_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *Config) GetTracking() []*PullRequest {
	if x != nil {
		return x.Tracking
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Update *PullRequest `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pullrequester_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pullrequester_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUpdate() *PullRequest {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pullrequester_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pullrequester_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{3}
}

type PullRequest_Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Pass   PullRequest_Check_Pass `protobuf:"varint,2,opt,name=pass,proto3,enum=pullrequester.PullRequest_Check_Pass" json:"pass,omitempty"`
}

func (x *PullRequest_Check) Reset() {
	*x = PullRequest_Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pullrequester_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRequest_Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest_Check) ProtoMessage() {}

func (x *PullRequest_Check) ProtoReflect() protoreflect.Message {
	mi := &file_pullrequester_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest_Check.ProtoReflect.Descriptor instead.
func (*PullRequest_Check) Descriptor() ([]byte, []int) {
	return file_pullrequester_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PullRequest_Check) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PullRequest_Check) GetPass() PullRequest_Check_Pass {
	if x != nil {
		return x.Pass
	}
	return PullRequest_Check_UNKNOWN
}

var File_pullrequester_proto protoreflect.FileDescriptor

var file_pullrequester_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x22, 0xb3, 0x02, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x6f, 0x66, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x73, 0x12, 0x38, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x68, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x61, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x83, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x52, 0x04, 0x70, 0x61, 0x73,
	0x73, 0x22, 0x27, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x53, 0x53, 0x10, 0x02, 0x22, 0x5b, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x75, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x12,
	0x36, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x43, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x10, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6a,
	0x0a, 0x14, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x75,
	0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x75, 0x6c, 0x6c,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pullrequester_proto_rawDescOnce sync.Once
	file_pullrequester_proto_rawDescData = file_pullrequester_proto_rawDesc
)

func file_pullrequester_proto_rawDescGZIP() []byte {
	file_pullrequester_proto_rawDescOnce.Do(func() {
		file_pullrequester_proto_rawDescData = protoimpl.X.CompressGZIP(file_pullrequester_proto_rawDescData)
	})
	return file_pullrequester_proto_rawDescData
}

var file_pullrequester_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pullrequester_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pullrequester_proto_goTypes = []interface{}{
	(PullRequest_Check_Pass)(0), // 0: pullrequester.PullRequest.Check.Pass
	(*PullRequest)(nil),         // 1: pullrequester.PullRequest
	(*Config)(nil),              // 2: pullrequester.Config
	(*UpdateRequest)(nil),       // 3: pullrequester.UpdateRequest
	(*UpdateResponse)(nil),      // 4: pullrequester.UpdateResponse
	(*PullRequest_Check)(nil),   // 5: pullrequester.PullRequest.Check
}
var file_pullrequester_proto_depIdxs = []int32{
	5, // 0: pullrequester.PullRequest.checks:type_name -> pullrequester.PullRequest.Check
	1, // 1: pullrequester.Config.tracking:type_name -> pullrequester.PullRequest
	1, // 2: pullrequester.UpdateRequest.update:type_name -> pullrequester.PullRequest
	0, // 3: pullrequester.PullRequest.Check.pass:type_name -> pullrequester.PullRequest.Check.Pass
	3, // 4: pullrequester.PullRequesterService.UpdatePullRequest:input_type -> pullrequester.UpdateRequest
	4, // 5: pullrequester.PullRequesterService.UpdatePullRequest:output_type -> pullrequester.UpdateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pullrequester_proto_init() }
func file_pullrequester_proto_init() {
	if File_pullrequester_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pullrequester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pullrequester_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pullrequester_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pullrequester_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pullrequester_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRequest_Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pullrequester_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pullrequester_proto_goTypes,
		DependencyIndexes: file_pullrequester_proto_depIdxs,
		EnumInfos:         file_pullrequester_proto_enumTypes,
		MessageInfos:      file_pullrequester_proto_msgTypes,
	}.Build()
	File_pullrequester_proto = out.File
	file_pullrequester_proto_rawDesc = nil
	file_pullrequester_proto_goTypes = nil
	file_pullrequester_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PullRequesterServiceClient is the client API for PullRequesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PullRequesterServiceClient interface {
	UpdatePullRequest(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type pullRequesterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPullRequesterServiceClient(cc grpc.ClientConnInterface) PullRequesterServiceClient {
	return &pullRequesterServiceClient{cc}
}

func (c *pullRequesterServiceClient) UpdatePullRequest(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/pullrequester.PullRequesterService/UpdatePullRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullRequesterServiceServer is the server API for PullRequesterService service.
type PullRequesterServiceServer interface {
	UpdatePullRequest(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedPullRequesterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPullRequesterServiceServer struct {
}

func (*UnimplementedPullRequesterServiceServer) UpdatePullRequest(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePullRequest not implemented")
}

func RegisterPullRequesterServiceServer(s *grpc.Server, srv PullRequesterServiceServer) {
	s.RegisterService(&_PullRequesterService_serviceDesc, srv)
}

func _PullRequesterService_UpdatePullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullRequesterServiceServer).UpdatePullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pullrequester.PullRequesterService/UpdatePullRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullRequesterServiceServer).UpdatePullRequest(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PullRequesterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pullrequester.PullRequesterService",
	HandlerType: (*PullRequesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePullRequest",
			Handler:    _PullRequesterService_UpdatePullRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pullrequester.proto",
}
