// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pullrequester.proto

package pullrequester

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullRequest_Check_Pass int32

const (
	PullRequest_Check_UNKNOWN PullRequest_Check_Pass = 0
	PullRequest_Check_FAIL    PullRequest_Check_Pass = 1
	PullRequest_Check_PASS    PullRequest_Check_Pass = 2
)

var PullRequest_Check_Pass_name = map[int32]string{
	0: "UNKNOWN",
	1: "FAIL",
	2: "PASS",
}

var PullRequest_Check_Pass_value = map[string]int32{
	"UNKNOWN": 0,
	"FAIL":    1,
	"PASS":    2,
}

func (x PullRequest_Check_Pass) String() string {
	return proto.EnumName(PullRequest_Check_Pass_name, int32(x))
}

func (PullRequest_Check_Pass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{0, 0, 0}
}

type PullRequest struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	NumberOfCommits      int32                `protobuf:"varint,2,opt,name=number_of_commits,json=numberOfCommits,proto3" json:"number_of_commits,omitempty"`
	Checks               []*PullRequest_Check `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	Shas                 []string             `protobuf:"bytes,4,rep,name=shas,proto3" json:"shas,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{0}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PullRequest) GetNumberOfCommits() int32 {
	if m != nil {
		return m.NumberOfCommits
	}
	return 0
}

func (m *PullRequest) GetChecks() []*PullRequest_Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

func (m *PullRequest) GetShas() []string {
	if m != nil {
		return m.Shas
	}
	return nil
}

func (m *PullRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PullRequest_Check struct {
	Source               string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Pass                 PullRequest_Check_Pass `protobuf:"varint,2,opt,name=pass,proto3,enum=pullrequester.PullRequest_Check_Pass" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PullRequest_Check) Reset()         { *m = PullRequest_Check{} }
func (m *PullRequest_Check) String() string { return proto.CompactTextString(m) }
func (*PullRequest_Check) ProtoMessage()    {}
func (*PullRequest_Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{0, 0}
}

func (m *PullRequest_Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest_Check.Unmarshal(m, b)
}
func (m *PullRequest_Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest_Check.Marshal(b, m, deterministic)
}
func (m *PullRequest_Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest_Check.Merge(m, src)
}
func (m *PullRequest_Check) XXX_Size() int {
	return xxx_messageInfo_PullRequest_Check.Size(m)
}
func (m *PullRequest_Check) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest_Check.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest_Check proto.InternalMessageInfo

func (m *PullRequest_Check) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *PullRequest_Check) GetPass() PullRequest_Check_Pass {
	if m != nil {
		return m.Pass
	}
	return PullRequest_Check_UNKNOWN
}

type Config struct {
	LastRun              int64          `protobuf:"varint,1,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	Tracking             []*PullRequest `protobuf:"bytes,2,rep,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

func (m *Config) GetTracking() []*PullRequest {
	if m != nil {
		return m.Tracking
	}
	return nil
}

type UpdateRequest struct {
	Update               *PullRequest `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUpdate() *PullRequest {
	if m != nil {
		return m.Update
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe1259dc1913b7, []int{3}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pullrequester.PullRequest_Check_Pass", PullRequest_Check_Pass_name, PullRequest_Check_Pass_value)
	proto.RegisterType((*PullRequest)(nil), "pullrequester.PullRequest")
	proto.RegisterType((*PullRequest_Check)(nil), "pullrequester.PullRequest.Check")
	proto.RegisterType((*Config)(nil), "pullrequester.Config")
	proto.RegisterType((*UpdateRequest)(nil), "pullrequester.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "pullrequester.UpdateResponse")
}

func init() { proto.RegisterFile("pullrequester.proto", fileDescriptor_bebe1259dc1913b7) }

var fileDescriptor_bebe1259dc1913b7 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xea, 0x40,
	0x18, 0xc5, 0xcd, 0x1f, 0xa3, 0x7e, 0xa2, 0x37, 0xce, 0xbd, 0x5c, 0x72, 0xe5, 0x16, 0x42, 0xa0,
	0x34, 0x74, 0x91, 0x45, 0x0a, 0xa5, 0x5d, 0x4a, 0xa0, 0x50, 0x5a, 0x54, 0x46, 0xa4, 0x8b, 0x2e,
	0x24, 0xa6, 0xa3, 0xa6, 0x26, 0x99, 0x74, 0x26, 0xd3, 0x17, 0xe8, 0x23, 0xf5, 0x05, 0x4b, 0x26,
	0xb1, 0x68, 0xc1, 0x76, 0x77, 0xbe, 0x33, 0x67, 0xe6, 0xfc, 0x48, 0x3e, 0xf8, 0x9d, 0x8b, 0x24,
	0x61, 0xe4, 0x45, 0x10, 0x5e, 0x10, 0xe6, 0xe5, 0x8c, 0x16, 0x14, 0xf5, 0x0e, 0x4c, 0xe7, 0x5d,
	0x85, 0xee, 0x54, 0x24, 0x09, 0xae, 0x1c, 0x64, 0x82, 0x26, 0x58, 0x62, 0x29, 0xb6, 0xe2, 0x76,
	0x70, 0x29, 0xd1, 0x39, 0x0c, 0x32, 0x91, 0x2e, 0x09, 0x5b, 0xd0, 0xd5, 0x22, 0xa2, 0x69, 0x1a,
	0x17, 0xdc, 0x52, 0x6d, 0xc5, 0x6d, 0xe2, 0x5f, 0xd5, 0xc1, 0x64, 0x15, 0x54, 0x36, 0xba, 0x02,
	0x23, 0xda, 0x90, 0x68, 0xcb, 0x2d, 0xcd, 0xd6, 0xdc, 0xae, 0x6f, 0x7b, 0x87, 0x08, 0x7b, 0x4d,
	0x5e, 0x50, 0x06, 0x71, 0x9d, 0x47, 0x08, 0x74, 0xbe, 0x09, 0xb9, 0xa5, 0xdb, 0x9a, 0xdb, 0xc1,
	0x52, 0x97, 0x5e, 0x16, 0xa6, 0xc4, 0x6a, 0x4a, 0x18, 0xa9, 0x87, 0x6f, 0x0a, 0x34, 0xe5, 0x4d,
	0xf4, 0x17, 0x0c, 0x4e, 0x05, 0x8b, 0x48, 0x0d, 0x5b, 0x4f, 0xe8, 0x1a, 0xf4, 0x3c, 0xe4, 0x15,
	0x62, 0xdf, 0x3f, 0xfd, 0x89, 0xc0, 0x9b, 0x86, 0x9c, 0x63, 0x79, 0xc5, 0x39, 0x03, 0xbd, 0x9c,
	0x50, 0x17, 0x5a, 0xf3, 0xf1, 0xdd, 0x78, 0xf2, 0x30, 0x36, 0x1b, 0xa8, 0x0d, 0xfa, 0xcd, 0xe8,
	0xf6, 0xde, 0x54, 0x4a, 0x35, 0x1d, 0xcd, 0x66, 0xa6, 0xea, 0x3c, 0x82, 0x11, 0xd0, 0x6c, 0x15,
	0xaf, 0xd1, 0x3f, 0x68, 0x27, 0x21, 0x2f, 0x16, 0x4c, 0x64, 0x92, 0x43, 0xc3, 0xad, 0x72, 0xc6,
	0x22, 0x43, 0x97, 0xd0, 0x2e, 0x58, 0x18, 0x6d, 0xe3, 0x6c, 0x6d, 0xa9, 0xf2, 0x73, 0x0c, 0x8f,
	0xc3, 0xe0, 0xcf, 0xac, 0x13, 0x40, 0x6f, 0x9e, 0x3f, 0x85, 0x05, 0xd9, 0xfd, 0x13, 0x1f, 0x0c,
	0x21, 0x0d, 0xd9, 0xf0, 0xfd, 0x33, 0x75, 0xd2, 0x31, 0xa1, 0xbf, 0x7b, 0x84, 0xe7, 0x34, 0xe3,
	0xc4, 0x7f, 0x86, 0x3f, 0x7b, 0x41, 0xc2, 0x66, 0x84, 0xbd, 0xc6, 0x11, 0x41, 0x18, 0x06, 0x55,
	0x72, 0x7f, 0x0d, 0xfe, 0x7f, 0xa9, 0x38, 0x00, 0x1a, 0x9e, 0x1c, 0x39, 0xad, 0x9a, 0x9c, 0xc6,
	0xd2, 0x90, 0xbb, 0x76, 0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xda, 0x4c, 0x7f, 0x82, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PullRequesterServiceClient is the client API for PullRequesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PullRequesterServiceClient interface {
	UpdatePullRequest(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type pullRequesterServiceClient struct {
	cc *grpc.ClientConn
}

func NewPullRequesterServiceClient(cc *grpc.ClientConn) PullRequesterServiceClient {
	return &pullRequesterServiceClient{cc}
}

func (c *pullRequesterServiceClient) UpdatePullRequest(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/pullrequester.PullRequesterService/UpdatePullRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullRequesterServiceServer is the server API for PullRequesterService service.
type PullRequesterServiceServer interface {
	UpdatePullRequest(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterPullRequesterServiceServer(s *grpc.Server, srv PullRequesterServiceServer) {
	s.RegisterService(&_PullRequesterService_serviceDesc, srv)
}

func _PullRequesterService_UpdatePullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullRequesterServiceServer).UpdatePullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pullrequester.PullRequesterService/UpdatePullRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullRequesterServiceServer).UpdatePullRequest(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PullRequesterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pullrequester.PullRequesterService",
	HandlerType: (*PullRequesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePullRequest",
			Handler:    _PullRequesterService_UpdatePullRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pullrequester.proto",
}
